# Generated by Django 4.1.7 on 2023-04-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.account')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('event_start_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_date', models.DateField()),
                ('event_end_time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('completed', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.category')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.event')),
            ],
        ),
    ]
