# Generated by Django 4.1.7 on 2023-04-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_event_category_id_alter_task_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='check_start_date',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_end_date__gte', models.F('event_start_date'))), name='check_start_date'),
        ),
    ]
