# Generated by Django 4.1.7 on 2023-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_remove_event_check_start_date_event_check_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
